### ISSUE TITLE
Access token from AWS Cognito > 100 chars

### ISSUE THREAD

**Issue by jethrobear** [dropseed/django-oauth-login#19]
Hi all,
I would like to check if the *_token fields be extended from 100 to ~1000 (966 from my access_token)

Issue seen:
<html><body>
<h1>DataError
       at /oauth/cognito/callback/</h1>
  <pre class="exception_value">(1406, "Data too long for column 'access_token' at row 1")</pre>
  

Request Method: | GET
-- | --
https://`***`/oauth/cognito/callback/?code=`***`&state=`***`
4.2.3
DataError
(1406, "Data too long for column 'access_token' at row 1")
/usr/local/lib/python3.10/dist-packages/MySQLdb/connections.py, line 254, in query
oauthlogin.views.OAuthCallbackView
/usr/bin/python3
3.10.12
['',  '`***`',  '/usr/lib/python310.zip',  '/usr/lib/python3.10',  '/usr/lib/python3.10/lib-dynload',  '/usr/local/lib/python3.10/dist-packages',  '/usr/lib/python3/dist-packages']
Wed, 02 Aug 2023 15:57:16 +0800

</body>
</html>

Sample access_token:
`ey*****************************************************************************************.ey*************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************.eD****************************************************************************************************************************************************************************************************************************************************************************************************************************************************`

**Comment by davegaeddert** [comment]
Closed by #20, released in 0.2.4.
