### ISSUE TITLE
Please provide a detail explanation about how to use your library

### ISSUE THREAD

**Issue by dbarrientostk** [dropseed/django-oauth-login#25]
I have trying to setup your library in my project, the examples are not clear.

**Comment by davegaeddert** [comment]
Hey @dbarrientostk — the notes here are really the best I can provide at the moment: https://github.com/dropseed/django-oauth-login?tab=readme-ov-file#usage

This library intentionally requires a little bit of work/code on your part. You may prefer something like https://github.com/pennersr/django-allauth instead if you're not a fan of the way this one works.
